version: '3.9'

services:
  blockscout:
    network_mode: "host"
    ports:
      - 4200:4000
    extends:
      file: ./services/blockscout.yml
      service: blockscout
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: "true"
        RELEASE_VERSION: 6.9.0
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://zoonet:8080/
        ETHEREUM_JSONRPC_TRACE_URL: http://zoonet:8080/
        ETHEREUM_JSONRPC_WS_URL: http://zoonet:8080/
        CHAIN_ID: '96369'
